### ISSUE TITLE
Create jupyter notebook of HBN phenotypic data classification of Anxiety; C++ lumberjack wrap in Py-RerF

### ISSUE THREAD

**Issue by ssankar6** [NeuroDataDesign/R-RerF#4]
DoD: 
(1). A Jupyter notebook with selected phenotypic data and classification and prediction of Anxiety. This will include: visualizations of the effects of changing RerF parameters, accuracy results based on different features selected, and other analysis that may come up. 
(2) Implementation of optimal default parameters for regression given a specific dataset. We would like to update num.trees, max depth, density/sparsity of the A matrix to determine the optimal defaults. We will run original default parameters vs updated parameters to check overall performance and accuracy improvements. 
(3) We'll use pybind 11 or another C++ wrapper to wrap currently written Lumberjack C++ code into python. Python will take in a CSV data file with observations, features, and labels -> hand it over to C++ through wrapping -> return pointers that point to the created forest. Prediction will take in each observation and use said pointers to return a majority class label.

**Comment by jovo** [comment]
be specific and measurable.

**Comment by jovo** [comment]
@hkim171 this is underspecific.  all tasks must be SMART goals
